channels:
  - defaults
dependencies:
  - pip
  - pip:
      - async-timeout==4.0.2
      - nltk
      - attrs==22.2.0
      - openai==0.26.5
      - beautifulsoup4==4.11.2
      - opencv-python==4.7.0.68
      - brotlipy==0.7.0
      - packaging==23.0
      - cachetools==5.3.0
      - Pillow==9.4.0
      - python-vlc
      - frozenlist==1.3.3
      - protobuf==4.22.0
      - google==3.0.0
      - tifffile==2022.10.10
      - twitchio==2.5.0
      - typing_extensions
      - wincertstore==0.2
      - google-api-core==2.11.0
      - yarl==1.8.2
      - google-auth==2.15.0
      - google-cloud==0.34.0
      - googleapis-common-protos==1.57.0
      - google-cloud-texttospeech
      - imageio==2.25.0
      - iso8601==1.1.0
      - llama-cpp-python==0.2.6
      - numpy==1.24.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - PyWavelets==1.4.1
      - rsa==4.9
      - scipy==1.10.0
      - soupsieve==2.4
      - multidict==6.0.4
      - aiohttp==3.8.4
      - networkx==3.0
      - aiosignal==1.3.1
